#+TITLE:  SNGeometry Manager Configuration
#+AUTHOR: Xavier Garrido
#+DATE:   2013-03-12
#+OPTIONS: ^:{}

* Introduction
The =sngeometry= library provides some geometry wrappers arround =geomtools=
library and dedicated to SuperNEMO detector description.

This file holds mainly the paths to geometry files most of them are placed in
=$SNGEOMETRY_DATA_DIR= directory.

* Manager configuration
:PROPERTIES:
:TANGLE: sngeometry_manager.conf
:END:

** Setup label, description and version
#+BEGIN_SRC sh
  #@description Setup label
  setup_label : string = "snemo"

  #@description Setup description
  setup_description : string = "SuperNEMO demonstrator module"

  #@description Setup version
  setup_version : string = "3.0"
#+END_SRC

** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "warning"
#+END_SRC

** Geometry factory
The geometry factory holds all the files needed for the geometry construction.

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority of the embedded geometry model factory
  factory.logging.priority : string = "warning"
#+END_SRC

*** Geometry files
#+BEGIN_SRC sh
  #@description List of files describing the geometry models
  factory.geom_files : string[22] as path =                                                                       \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/source_module/source_calibration.geom"            \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/source_module/source_frame_horizontal_beams.geom" \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/source_module/source_frame_vertical_beams.geom"   \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/source_module/source_strips.geom"                 \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/source_module/source_foil_support.geom"           \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/source_module/source_module.geom"                 \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/pmt_5inch.geom"                   \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/xwall_module.geom"                \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/xwall.geom"                       \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/gveto_module.geom"                \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/gveto.geom"                       \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/tracker_drift_cell_base.geom"     \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/tracker_drift_cell_nodes.geom"    \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/tracker_layers.geom"              \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/tracker_volumes.geom"             \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/tracker_modules/tracker_submodules.geom"          \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/calorimeter_modules/pmt_8inch.geom"               \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/calorimeter_modules/calorimeter_module.geom"      \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/calorimeter_modules/calorimeter_walls.geom"       \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/calorimeter_modules/calorimeter_submodules.geom"  \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/module_0.geom"                                    \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/setup.geom"
#+END_SRC

** ID manager
*** Logging priority
#+BEGIN_SRC sh
  #@description Logging flag of the embedded ID manager
  id_mgr.logging.priority : string = "warning"
#+END_SRC

*** Category list
Categories are used to assign a unique id number (integer) to a geometrical
volume.
#+BEGIN_SRC sh
  #@description Source file of the geometry categories used by the ID manager
  id_mgr.categories_list : string as path = \
      "${SNGEOMETRY_DATA_DIR}/resources/setups/snemo/config_3.0/categories.lis"
#+END_SRC

** Mapping configuration
#+BEGIN_SRC sh
  #@description Build the embedded mapping dictionnary
  build_mapping : boolean = 0

  #@description Max depth of the mapping: no items to be mapped
  mapping.max_depth : integer = 0

  #@description Categories not to be registered in the mapping dictionnary
  mapping.excluded_categories : string[5] = \
      "drift_cell_field_wires_set" \
      "drift_cell_field_wire"      \
      "drift_cell_base"            \
      "drift_cell_cathodic_ring"   \
      "drift_cell_anodic_wire"
#+END_SRC

** Plugins configuration
#+BEGIN_SRC sh
  #@description Plugins factory preload from system registration (default=0)
  plugins.factory_no_preload : boolean = 0

  #@description Plugins initialization at load (default=0)
  plugins.force_initialization_at_load : boolean = 0

  #@description Configuration files for geometry manager's plugins
  plugins.configuration_files : string[3] as path =                                        \
      "${SNAILWARE_SIMULATION_DIR}/snemo_configuration/current/materials_plugin.conf"      \
      "${SNAILWARE_SIMULATION_DIR}/snemo_configuration/current/magnetic_field_plugin.conf" \
      "${SNAILWARE_SIMULATION_DIR}/snemo_configuration/current/locator_plugin.conf"
#+END_SRC

* Material for SuperNEMO detector
** Material driver
:PROPERTIES:
:TANGLE:    materials_plugin.conf
:END:

We use the definitions of isotopes, elements and materials from the installed
materials library. Here the =materials_aliases= definition are locally defined
to change the source foil isotope.
*** Plugin declaration
#+BEGIN_SRC sh
  #@description The geometry manager plugin for materials

  #@key_label  "name"
  #@meta_label "type"

  [name="materials_driver" type="geomtools::materials_plugin"]
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "warning"
#+END_SRC

*** Files
#+BEGIN_SRC sh
  #@description List of files describing the materials
  materials.files : string[6] as path =                          \
      "@materials:data/std_isotopes.def"    \
      "@materials:data/std_elements.def"    \
      "@materials:data/std_materials.def"   \
      "${SNGEOMETRY_DATA_DIR}/resources/materials/elements.def"  \
      "${SNGEOMETRY_DATA_DIR}/resources/materials/materials.def" \
      "${SNAILWARE_SIMULATION_DIR}/snemo_configuration/current/materials_aliases.def"
#+END_SRC

** Material aliases
:PROPERTIES:
:TANGLE: materials_aliases.def
:END:

#+BEGIN_SRC sh
  #@description A sample list of elements
  #@key_label   "name"
  #@meta_label  "type"

  [name="vacuum" type="alias"]
  #@description The alias for vacuum
  material : string = "std::vacuum"

  [name="glass" type="alias"]
  #@description The alias for glass
  material : string = "std::pyrex"

  [name="tracking_gas" type="alias"]
  #@description The alias for tracking gas
  material : string = "snemo::nemo3_tracking_gas"

  [name="copper" type="alias"]
  #@description The alias for metal
  material : string = "std::copper"

  [name="iron" type="alias"]
  #@description The alias for metal
  material : string = "std::iron"

  [name="ENVINET_PS_scintillator" type="alias"]
  #@description The alias for X-walls plastic scintillator
  material : string = "std::NE110"

  [name="Dubna_PS_scintillator" type="alias"]
  #@description The alias for gamma veto plastic scintillator
  material : string = "std::NE110"

  [name="PVT_scintillator" type="alias"]
  #@description The alias for PVT plastic scintillator
  material : string = "std::PVT"

  [name="scin_wrapper" type="alias"]
  #@description The alias for plastic scintillator wrapping material
  material : string = "std::mylar"

  [name="frame_metal" type="alias"]
  #@description The alias for the frames material
  material : string = "std::iron"

  [name="wire_metal" type="alias"]
  #@description The alias for the wire material
  material : string = "std::inox"

  [name="lab_air" type="alias"]
  #@description The alias for the air gas in the lab
  material : string = "snemo::lab_air"

  [name="nitrogen" type="alias"]
  #@description The alias for the nitrogen gas
  material : string = "snemo::nitrogen"

  [name="bb_source_material" type="alias"]
  #@description The alias for the source
  material : string = "snemo::se82_source_material"

  [name="RTV" type="alias"]
  #@description The alias for the RTV material
  material : string = "std::water"

  [name="SBR" type="alias"]
  #@description The alias for the SBR material
  material : string = "std::water"

  [name="PFTE" type="alias"]
  #@description The alias for the PFTE material
  material : string = "std::mylar"
#+END_SRC

* Magnetic field for SuperNEMO detector
** Magnetic field plugin
:PROPERTIES:
:TANGLE: magnetic_field_plugin.conf
:END:

*** Plugin declaration
#+BEGIN_SRC sh
  #@description The geometry manager plugin for emfield

  #@key_label  "name"
  #@meta_label "type"

  [name="fields_driver" type="emfield::emfield_geom_plugin"]
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "warning"
#+END_SRC

*** EM field manager configuration
#+BEGIN_SRC sh
  #@description Manager logging priority
  manager.logging.priority : string = "warning"

  #@description The name of the geometry service
  manager.services.geometry : string = "Geo"

  #@description List of EM fields definitions files
  manager.field_definitions_filenames : string[1] as path = \
      "${SNAILWARE_SIMULATION_DIR}/snemo_configuration/current/magnetic_field_drivers.conf"
#+END_SRC

EM field defined within =manager.field_definitions_filenames= file can be set
independently and at the same time for different G4 volumes. This association
between volumes and field is done by the =geom_map= object of =emfield=
component. For SuperNEMO, constant magnetic field is defined inside demonstrator
module.
#+BEGIN_SRC sh
  #@description Flag to activate the geometry volume/field associations map
  manager.build_geom_map : boolean = 1

  #@description Manager logging priority
  manager.geom_map.logging.priority : string = "warning"

  #@description The list of EM fields associated to some logical volumes
  manager.geom_map.associations.labels : string[1] = "sn_module"

  #@description The logical model associated for the label 'tracker'
  manager.geom_map.associations.sn_module.volume : string = "module_basic.model.log"

  #@description The EM field associated for the label "tracker"
  manager.geom_map.associations.sn_module.field_name : string = "B_module"
#+END_SRC

** Magnetic field drivers
:PROPERTIES:
:TANGLE: magnetic_field_drivers.conf
:END:

*** Driver preamble
#+BEGIN_SRC sh
  #@description Definition parameters for some electro-magnetic fields

  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Constant magnetic field
#+BEGIN_SRC sh
  [name="B_module" type="emfield::uniform_magnetic_field"]

  #@config Configuration parameters for the magnetic field of SuperNEMO

  #@description Default implicit magnetic field unit
  magnetic_field.unit        : string  = "gauss"

  #@description Coordinates of the static magnetic field (Bx, By, Bz)
  magnetic_field.coordinates : real[3] = 0.0 0.0 25.0
#+END_SRC
* Locators for SuperNEMO detector
** Locator driver
:PROPERTIES:
:TANGLE: locator_plugin.conf
:END:

*** Plugin declaration
#+BEGIN_SRC sh
  #@description The geometry manager plugin for locators

  #@key_label  "name"
  #@meta_label "type"

  [name="locator_driver" type="snemo::geometry::locator_plugin"]
#+END_SRC

*** Logging priority
#+BEGIN_SRC sh
  #@description Logging priority
  logging.priority : string = "warning"
#+END_SRC

*** Module number
#+BEGIN_SRC sh
  #@description SuperNEMO module number
  locators.module_number : integer = 0
#+END_SRC
