#+TITLE:  SNGenvertex Manager Configuration
#+AUTHOR: Xavier Garrido
#+DATE:   2013-10-20
#+OPTIONS: ^:{}

* Introduction
This file holds some vertex generators related to SuperNEMO detector geometry.

* Manager configuration
:PROPERTIES:
:HEADER-ARGS: :tangle sngenvertex_manager.conf
:END:

** Logging priority
#+BEGIN_SRC shell
  #@description Logging priority
  logging.priority : string = @variant(core:logging_priority|"warning")
#+END_SRC

** Vertices list of files
The following code defines the location of several vertices files. All of them
are defined in Section [[Vertex configuration]].

#+BEGIN_SRC shell
  #@variant_if geometry:layout/if_basic|true

  #@description Names of the files configuring the list of registered vertex generators
  vg_list : string[5] as path =                                                            \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/scin_vg.lis"    \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/tracker_vg.lis" \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/shield_vg.lis"  \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/source_vg.lis"  \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/source_calibration_vg.lis"

  #@description The name of the default vertex generator to be used
  #@variant_only !geometry:layout/if_basic/source_calibration/is_active|true
  generator : string = "source_pads_bulk"

  #@variant_only geometry:layout/if_basic/source_calibration/is_active|false
  generator : string = "source_calibration_all_spots"

  #@variant_endif

  #@variant_if geometry:layout/if_half_commissioning|false
  #@description Names of the files configuring the list of registered vertex generators
  vg_list : string[3] as path =                                                            \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/scin_vg.lis"    \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/tracker_vg.lis" \
    "@falaise:config/snemo/demonstrator/simulation/vertexes/4.0/generators/commissioning_vg.lis"

  #@description The name of the default vertex generator to be used
  generator : string = "all_commissioning_spots"

  #@variant_endif
#+END_SRC

#+BEGIN_SRC shell :tangle no
  #@description Names of the files configuring the list of registered vertex generators
  vg_list : string[5] as path =     \
    "@configuration:scin_vg.lis"    \
    "@configuration:tracker_vg.lis" \
    "@configuration:source_vg.lis"  \
    "@configuration:hall_vg.lis"    \
    "@configuration:calibration_vg.lis"
#+END_SRC

* Vertex configuration
This section defines several vertices configuration :
- [[Scintillator vertices][Scintillator vertices]]: to generate external events coming from calorimeter
  walls,
- [[Tracker vertices][Tracker vertices]]: to generate events from the internal drift chamber either on
  wires surface or inside gas tracking,
- [[Source vertices][Source vertices]]: to produce 2\beta events or to simulate source contamination.
- [[External vertices][External vertices]]: to generate events from outside the detector like neutrons

** Scintillator vertices
:PROPERTIES:
:HEADER-ARGS: :tangle scin_vg.lis
:END:

Insert preamble
#+BEGIN_SRC shell
  #@description A list of vertex generators
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

- Generate vertex in the bulk volume of the wrapper for the main calorimeter's
  scintillator blocks:

  #+BEGIN_SRC shell
    [name="calo_wrapper_bulk" type="genvtx::box_model_vg"]

    #@config Vertex generation from the bulk of the main calorimeter wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    #origin : string = "category=calorimeter_wrapper module={*} side={1} column={0;1;2;4;19} row={0;1;2;12;13}"
    origin : string = "category='calorimeter_wrapper' module={*} side={*} column={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

- Generate vertex in the bulk volume of the wrapper for the X-calorimeter's
  scintillator blocks:

  #+BEGIN_SRC shell
    [name="xcalo_wrapper_bulk" type="genvtx::box_model_vg"]

    #@config Vertex generation from the bulk of the X-wall calorimeter wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='xcalo_wrapper' module={*} side={*} column={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

- Generate vertex in the bulk volume of the wrapper for the \gamma veto
  calorimeter's scintillator blocks:

  #+BEGIN_SRC shell
    [name="gveto_wrapper_bulk" type="genvtx::box_model_vg"]

    #@config Vertex generation from the bulk of the gamma veto wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='gveto_wrapper' module={*} side={*} wall={*} column={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

- Generate vertex from the surface of the main calorimeter's scintillator blocks:

  #+BEGIN_SRC shell
    [name="calo_wrapper_surface" type="genvtx::box_model_vg"]

    #@config Vertex generation from the surface of the main calorimeter wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='calorimeter_wrapper' module={*} side={*} column={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box top face activation
    mode.surface.top  : boolean = true
  #+END_SRC

- Generate vertex from the surface of the X-calorimeter's scintillator blocks:

  #+BEGIN_SRC shell
    [name="xcalo_wrapper_surface" type="genvtx::box_model_vg"]

    #@config Vertex generation from the surface of the X-wall calorimeter wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='xcalo_wrapper' module={*} side={*} column={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box top face activation
    mode.surface.top  : boolean = true
  #+END_SRC

- Generate vertex from the surface of the \gamma veto's scintillator blocks:

  #+BEGIN_SRC shell
    [name="gveto_wrapper_surface" type="genvtx::box_model_vg"]

    #@config Vertex generation from the surface of the gamma veto wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='gveto_wrapper' module={*} side={*} wall={*} column={*}"

    #@description Generation mode ("surface" or "bulk")
    mode : string = "surface"

    #@description Surface mode box top face activation
    mode.surface.top : boolean = true
  #+END_SRC

- Generate vertex in the PMT glass

  #+BEGIN_SRC shell
    [name="pmt_glass_bulk" type="genvtx::polycone_model_vg"]

    #@config Vertex generation from the bulk of the PMT glass wrapper

    #@description Logging priority
    logging.priority : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='calorimeter_pmt_glass' module={*} side={*} column={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode : string = "bulk"

    #@description Generation within polycone material
    mode.bulk.body : boolean = true

    #@description Generate vertex on all polycone frustrum
    polycone.all_frustrum : boolean = true
  #+END_SRC

- Generate vertex in the bulk volume of the scintillator of the main
  calorimeter's scintillator blocks:

  #+BEGIN_SRC shell
    [name="calo_scin_bulk" type="genvtx::box_model_vg"]

      #@config Vertex generation from 'tracking_gas' material

      #@description Logging priority
      logging.priority  : string = @variant(core:logging_priority|"warning")

      #@description Geometry version requirement (not working with version lower than 3.0)
      geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

      #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
      origin : string = "category='calorimeter_optical_module' module={*} side={*} column={*} row={*}"

      #@description Use bounding box method to shoot vertex in complicated form
      use_bounding_box : boolean = true

      #@description Generation mode ("surface" or "bulk")
      mode   : string = "bulk"
  #+END_SRC

  Here starts the validation configuration. We first add a support to vertex
  validation
  #+BEGIN_SRC shell
    #@description Vertex validation support
    vertex_validation_support : boolean = true
  #+END_SRC
  we define the logging level
  #+BEGIN_SRC shell
    #@description Maximum number of tries for the rejection method
    validation.logging.priority : string = @variant(core:logging_priority|"warning")
  #+END_SRC
  and we activate it
  #+BEGIN_SRC shell
    #@description Vertex validation activation
    validation.activation : boolean = true
  #+END_SRC

  We also defines the maximum number of tries for the rejection process; above this
  number the vertex generator throws an error.
  #+BEGIN_SRC shell
    #@description Maximum number of tries for the rejection method
    validation.maximum_number_of_tries : integer = 1000
  #+END_SRC

  We finally define the validation id which refers to the =cut= identifiant with
  which the validator is registered. Here we want to only keep vertex within the
  =tracking_gas= material so we use a =in_materials_vertex_validator=
  #+BEGIN_SRC shell
    #@description Vertex validation id
    validation.validator_id : string = "genvtx::in_materials_vertex_validator"
  #+END_SRC
  and we define the set of materials to be used
  #+BEGIN_SRC shell
    #@description List of materials to be used
    validation.validator_params.materials.ref : string[1] = "ENVINET_PS_scintillator"
  #+END_SRC

  We can also set the logging priority and the maximum depth to look inside
  #+BEGIN_SRC shell
    # #@description Logging level for validator
    # validation.validator_params.max_depth : integer = 100

    #@description Logging level for validator
    validation.validator_params.logging.priority : string = @variant(core:logging_priority|"warning")
  #+END_SRC

** Tracker vertices
:PROPERTIES:
:HEADER-ARGS: :tangle tracker_vg.lis
:END:

Insert preamble
#+BEGIN_SRC shell
  #@description A list of vertex generators
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Vertices on tracker wires

- Generate vertex from the bulk volume of the anode wires:

  #+BEGIN_SRC shell
    [name="anode_wire_bulk" type="genvtx::cylinder_model_vg"]

    #@config Vertex generation from the bulk volume of the anode wires

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='drift_cell_anodic_wire' module={*} side={*} layer={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

- Generate vertex on the surface of the anode wires:

  #+BEGIN_SRC shell
    [name="anode_wire_surface" type="genvtx::cylinder_model_vg"]

    #@config Vertex generation from the surface of the anode wires

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='drift_cell_anodic_wire' module={*} side={*} layer={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box side face activation
    mode.surface.side   : boolean = true

    #@description Surface mode box bottom face activation
    mode.surface.bottom : boolean = false

    #@description Surface mode box top face activation
    mode.surface.top    : boolean = false
  #+END_SRC

- Generate vertex on the surface of the field wires:

  #+BEGIN_SRC shell
    [name="field_wire_surface" type="genvtx::cylinder_model_vg"]

    #@config Vertex generation from the surface of the field wires

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='drift_cell_field_wire' module={*} side={*} layer={*} row={*} set={*} wire={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box side face activation
    mode.surface.side   : boolean = true

    #@description Surface mode box bottom face activation
    mode.surface.bottom : boolean = false

    #@description Surface mode box top face activation
    mode.surface.top    : boolean = false
  #+END_SRC

- Generate vertex from the bulk volume of the field wires:

  #+BEGIN_SRC shell
    [name="field_wire_bulk" type="genvtx::cylinder_model_vg"]

    #@config Vertex generation from the bulk volume of the anode wires

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='drift_cell_field_wire' module={*} side={*} layer={*} row={*}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

*** Vertices within tracker volumes (wires included)
**** Generator using category list
This vertex generator is quite classical in the way that it uses the category
file list and especially, the =drift_cell_core= category. This means that
vertices are going to be generated in the cell core, wires included, but not
inside the gap between foil and first tracker layer as well as not within the
gap between the main calorimeter walls and the last tracker layer. In order to
get a full coverage of tracker gaz, you may have a look to the next section.

#+BEGIN_SRC shell
  [name="tracker_drift_cell_bulk" type="genvtx::box_model_vg"]

  #@config Vertex generation from the core of Geiger cell

  #@description Logging priority
  logging.priority  : string = @variant(core:logging_priority|"warning")

  #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
  origin : string = "category='drift_cell_core' module={*} side={*} layer={*} row={*}"

  #@description Generation mode ("surface" or "bulk")
  mode   : string = "bulk"
#+END_SRC

**** Vertex generator using hardcoded geometry position
The following vertex generator defines a box which dimensions are hardcoded by
following the dimensions between source foil and calroimeter walls. This means
that any change in the geometry setup like an increase of source foil thickness
will need to update this box dimensions. Nevertheless, this vertex generator
allows to shoot events from the full tracker volumes so basically where tracker
gaz will remain.

To calculate the box size and the box placement, the following dimensions have
been used :
- tracker volume is a box of 405\times5008\times3030 mm,
- the source core model has a thickness of 58 mm,
- the source foil thickness is 167 µm.

#+BEGIN_SRC shell
  [name="tracker_volume_box" type="genvtx::box_vg"]

  #@config Vertex generation from the tracker gaz

  #@description Logging priority
  logging.priority  : string = @variant(core:logging_priority|"warning")

  #@description Generation mode ("surface" or "bulk")
  mode   : string = "bulk"

  #@description Box x size
  box.x : real as length =  433.9165 mm

  #@description Box y size
  box.y : real as length = 5008.0 mm

  #@description Box z size
  box.z : real as length = 3030.0 mm
#+END_SRC

Then we define 2 placements : one for the front part ($x>0$) of the tracker and
another one for the back part ($x<0$).

#+BEGIN_SRC shell
  [name="tracker_front_volume_bulk" type="genvtx::placement_vg"]

  #@config Vertex generation from the front tracker volume

  #@description Logging priority
  logging.priority  : string = @variant(core:logging_priority|"warning")

  #@description Vertex generator name to place
  vertex_generator.name : string = "tracker_volume_box"

  #@description Placement along x-axis
  placement.x : real as length = 217.04175 mm

  #@description Placement along y-axis
  placement.y : real as length = 0.0 mm

  #@description Placement along z-axis
  placement.z : real as length = 0.0 mm
#+END_SRC

#+BEGIN_SRC shell
  [name="tracker_back_volume_bulk" type="genvtx::placement_vg"]

  #@config Vertex generation from the front tracker volume

  #@description Logging priority
  logging.priority  : string = @variant(core:logging_priority|"warning")

  #@description Vertex generator name to place
  vertex_generator.name : string = "tracker_volume_box"

  #@description Placement along x-axis
  placement.x : real as length = -217.04175 mm

  #@description Placement along y-axis
  placement.y : real as length = 0.0 mm

  #@description Placement along z-axis
  placement.z : real as length = 0.0 mm
#+END_SRC

We finally define a combined vertex generator in order to mix the two previous
vertex generators:
#+BEGIN_SRC shell
  [name="tracker_volume_bulk" type="genvtx::combined_vg"]

  #@config Vertex generation from the bulk volume of the tracker

  #@description Logging priority
  logging.priority  : string = @variant(core:logging_priority|"warning")

  #@description Geometry version requirement (not working with version lower than 2.0)
  geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

  #@description Vertex generator names
  generators : string[2]  = "tracker_front_volume_bulk" "tracker_back_volume_bulk"

  #@description Absolute weight of different generators
  generators.tracker_front_volume_bulk.absolute_weight : real = 1.0
  generators.tracker_back_volume_bulk.absolute_weight  : real = 1.0
#+END_SRC

**** Vertex generator with validator

We finally use a rejection method based on changes from
https://nemo.lpc-caen.in2p3.fr/changeset/15140/genvtx/trunk. The idea is to
shoot vertex within SuperNEMO module and then reject the ones not inside
=tracking_gas=.

#+BEGIN_SRC shell
  [name="tracker_gas_bulk" type="genvtx::box_model_vg"]

  #@config Vertex generation from 'tracking_gas' material

  #@description Logging priority
  logging.priority  : string = @variant(core:logging_priority|"warning")

  #@description Geometry version requirement (not working with version lower than 3.0)
  geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

  #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
  origin : string = "category='module' module={*}"

  #@description Generation mode ("surface" or "bulk")
  mode   : string = "bulk"
#+END_SRC

***** Vertex validation
Here starts the validation configuration. We first add a support to vertex
validation
#+BEGIN_SRC shell
  #@description Vertex validation support
  vertex_validation_support : boolean = true
#+END_SRC
we define the logging level
#+BEGIN_SRC shell
  #@description Maximum number of tries for the rejection method
  validation.logging.priority : string = @variant(core:logging_priority|"warning")
#+END_SRC
and we activate it
#+BEGIN_SRC shell
  #@description Vertex validation activation
  validation.activation : boolean = true
#+END_SRC

We also defines the maximum number of tries for the rejection process; above this
number the vertex generator throws an error.
#+BEGIN_SRC shell
  #@description Maximum number of tries for the rejection method
  validation.maximum_number_of_tries : integer = 1000
#+END_SRC

We finally define the validation id which refers to the =cut= identifiant with
which the validator is registered. Here we want to only keep vertex within the
=tracking_gas= material so we use a =in_materials_vertex_validator=
#+BEGIN_SRC shell
  #@description Vertex validation id
  validation.validator_id : string = "genvtx::in_materials_vertex_validator"
#+END_SRC
and we define the set of materials to be used
#+BEGIN_SRC shell
  #@description List of materials to be used
  validation.validator_params.materials.ref : string[1] = "tracking_gas"
#+END_SRC

We can also set the logging priority and the maximum depth to look inside
#+BEGIN_SRC shell
  # #@description Logging level for validator
  # validation.validator_params.max_depth : integer = 100

  #@description Logging level for validator
  validation.validator_params.logging.priority : string = @variant(core:logging_priority|"warning")
#+END_SRC

** Source vertices
:PROPERTIES:
:HEADER-ARGS: :tangle source_vg.lis
:END:

Since there are two types of source pads namely "internal" and "external" with
different size and then different isotope mass, we first define independent
vertices for each of this model and then use a =genvtx::combined_vg= model to
combine with appropriate weights. These vertices are only available with
SuperNEMO geometry version greater than 2.0.

Insert preamble
#+BEGIN_SRC shell
  #@description A list of vertex generators
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

*** Internal source pads
- Generate vertex from the bulk volume of the source foil:
  #+BEGIN_SRC shell
    [name="source_pads_internal_bulk" type="genvtx::box_model_vg"]

    #@config Vertex generation from the bulk volume of the inner source pads

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry version requirement (not working with version lower than 2.0)
    geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='source_strip' module={*} strip=[1;34]"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

- Generate vertex from the surface of the source foil:
  #+BEGIN_SRC shell
    [name="source_pads_internal_surface" type="genvtx::box_model_vg"]

    #@config Vertex generation from the surface of the inner source pads

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry version requirement (not working with version lower than 2.0)
    geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='source_strip' module={*} strip=[1;34]"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box back face activation
    mode.surface.back  : boolean = true

    #@description Surface mode box front face activation
    mode.surface.front : boolean = true
  #+END_SRC

*** External source pads

- Generate vertex from the bulk volume of the source foil:
  #+BEGIN_SRC shell
    [name="source_pads_external_bulk" type="genvtx::box_model_vg"]

    #@config Vertex generation from the bulk volume of the outer source pads

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry version requirement (not working with version lower than 2.0)
    geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='source_strip' module={*} strip={0;35}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC

- Generate vertex from the surface of the source foil:
  #+BEGIN_SRC shell
    [name="source_pads_external_surface" type="genvtx::box_model_vg"]

    #@config Vertex generation from the surface of the outer source pads

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry version requirement (not working with version lower than 2.0)
    geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='source_strip' module={*} strip={0;35}"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box back face activation
    mode.surface.back  : boolean = true

    #@description Surface mode box front face activation
    mode.surface.front : boolean = true
  #+END_SRC

*** Combined vertex

- Generate vertex from both the bulk volume of all the source foils:
  #+BEGIN_SRC shell
    [name="source_pads_bulk" type="genvtx::combined_vg"]

    #@config Vertex generation from the bulk volume of the source pads

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry version requirement (not working with version lower than 2.0)
    geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

    #@description Vertex generator names
    generators : string[2]  = "source_pads_external_bulk" "source_pads_internal_bulk"

    #@description Absolute weight of different generators
    generators.source_pads_external_bulk.absolute_weight : real = 0.054
    generators.source_pads_internal_bulk.absolute_weight : real = 1.0
  #+END_SRC

- Generate vertex from the surface of all the source foils:
  #+BEGIN_SRC shell
    [name="source_pads_surface" type="genvtx::combined_vg"]

    #@config Vertex generation from the surface of the source pads

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"warning")

    #@description Geometry version requirement (not working with version lower than 2.0)
    geometry.setup_requirement : string = "snemo::demonstrator(>=3)"

    #@description Vertex generator names
    generators : string[2] = \
      "source_pads_internal_surface" \
      "source_pads_external_surface"

    #@description Absolute weight of different generators
    generators.source_pads_external_surface.absolute_weight : real  = 0.054
    generators.source_pads_internal_surface.absolute_weight : real  = 1.0
  #+END_SRC
** External vertices
:PROPERTIES:
:HEADER-ARGS: :tangle hall_vg.lis
:END:

Insert preamble
#+BEGIN_SRC shell
  #@description A list of vertex generators
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

- Generate vertex from the surface of the hall walls
  #+BEGIN_SRC shell
    [name="experimental_hall_surface" type="genvtx::box_model_vg"]

    #@config Vertex generation from the surface of the experimental hall

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"notice")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='hall'"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "surface"

    #@description Surface mode box back face activation
    mode.surface.back   : boolean = true

    #@description Surface mode box front face activation
    mode.surface.front  : boolean = true

    #@description Surface mode box bottom face activation
    mode.surface.bottom : boolean = true

    #@description Surface mode box top face activation
    mode.surface.top    : boolean = true

    #@description Surface mode box left face activation
    mode.surface.left   : boolean = true

    #@description Surface mode box right face activation
    mode.surface.right  : boolean = true
  #+END_SRC

- Generate vertex from the volume of the hall
  #+BEGIN_SRC shell
    [name="experimental_hall_bulk" type="genvtx::box_model_vg"]

    #@config Vertex generation from the volume of the experimental hall

    #@description Logging priority
    logging.priority  : string = @variant(core:logging_priority|"notice")

    #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
    origin : string = "category='hall'"

    #@description Generation mode ("surface" or "bulk")
    mode   : string = "bulk"
  #+END_SRC
** Calibration source vertices
:PROPERTIES:
:HEADER-ARGS: :tangle calibration_vg.lis
:END:

Insert preamble
#+BEGIN_SRC shell
  #@description A list of source calibration vertex generators
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

#+BEGIN_SRC shell
  [name="calibration_source_bulk" type="genvtx::cylinder_model_vg"]

  #@config Vertex generation from the bulk of the calibration sources

  #@description Logging priority
  logging.priority : string = @variant(core:logging_priority|"warning")

  #@description Geometry origin of vertex in term of geometry category and addresses (geom ID)
  origin : string = "category='calibration_spot' module={*} path={*} position={*}"

  #@description Generation mode ("surface" or "bulk")
  mode   : string = "bulk"
#+END_SRC
