#+TITLE:  SNGenbb Manager Configuration
#+AUTHOR: Xavier Garrido
#+DATE:   2013-03-04
#+OPTIONS: ^:{}
#+STARTUP: entitiespretty

* Introduction

The =genbb= package is dedicated to the generation of double beta decay and/or
radioactive background primary events as input for a simulation program.

More details concerning the use of =genbb= can be found in [[https://nemo.lpc-caen.in2p3.fr/wiki/genbb_help][LPC wiki]].

* Manager configuration
:PROPERTIES:
:TANGLE: sngenbb_manager.conf
:END:
** Genbb manager configuration
Here, general options such as verbosity, debug flags are passed to =genbb=
manager.
#+BEGIN_SRC sh
  #@config Main configuration parameters for the genbb manager

  #@description Logging priority
  logging.priority : string = "warning"

  #@description List of files containing particle generator definition rules
  generators.configuration_files : string[5] as path = \
      "@falaise:config/common/simulation/primary_events/1.0/background.def"  \
      "@falaise:config/common/simulation/primary_events/1.0/calibration.def" \
      "@falaise:config/common/simulation/primary_events/1.0/dbd.def"         \
      "@falaise:config/common/simulation/primary_events/1.0/misc.def"        \
      "${SNAILWARE_SIMULATION_DIR}/snemo_configuration/current/sngenbb_wrappers.conf"
#+END_SRC

* Genbb wrappers
:PROPERTIES:
:TANGLE: sngenbb_wrappers.conf
:END:

This section holds the configuration of several =genbb= wrappers.

#+BEGIN_SRC sh
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

** Radioelement wrappers
This part basically provides additionnal event generator wrappers for
SuperNEMO.

*** \nbsp^{214}Pb \beta\beta0\nu
Following a [[http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=2946][talk]] given by Vladimir Treytak during Bratislava collaboration
meeting, 2013,\nbsp^{214}Pb is also a 2\beta emitter
#+BEGIN_SRC sh
  [name="bb0nu_Pb214" type="genbb::wdecay0"]
  #@config Neutrinoless double beta decay of Pb-214 [DBD]
  decay_type      : string  = "DBD"
  decay_isotope   : string  = "Pb214"
  decay_dbd_level : integer = 0
  decay_dbd_mode  : integer = 1
#+END_SRC

** Single particle generator
Here, single particle can be generated using different energy distribution : fix
energy, flat energy distribution given energy limits, gaussian energy
distribution or following a tabulated energy spectrum.

*** Single electron with flat energy distribution
#+BEGIN_SRC sh
  [name="electron_0-3MeV_flat" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Seed for the embedded random number generator:
  seed                  : integer = 314159

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name         : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode                  : string = "energy_range"

  ### Only for "energy_range" mode:
  min_energy            : real   = 0000.
  max_energy            : real   = 3000.
  energy_unit           : string = "keV"

  ### Only for "gaussian_energy" mode:
  #mean_energy           : real   = 1000.
  #sigma_energy          : real   =  100.
  #energy_unit           : string = "keV"

  ### Only for "monokinetic" mode:
  #energy                : real   = 5500.
  #energy_unit           : string = "keV"

  ### Only for "spectrum" mode:
  #spectrum.data_file    : string = "${SNGENBB_DATA_DIR}/testing/data/sample_tabulated_energy_spectrum.data"

  randomized_direction   : boolean = 1
#+END_SRC

*** Single gamma with flat energy distribution
#+BEGIN_SRC sh
  [name="gamma_0-3MeV_flat" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Seed for the embedded random number generator:
  seed                  : integer = 314159

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name         : string = "gamma"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode                  : string = "energy_range"

  ### Only for "energy_range" mode:
  min_energy            : real   = 1000.
  max_energy            : real   = 1000.
  energy_unit           : string = "keV"

  ### Only for "gaussian_energy" mode:
  #mean_energy           : real   = 1000.
  #sigma_energy          : real   =  100.
  #energy_unit           : string = "keV"

  ### Only for "monokinetic" mode:
  #energy                : real   = 5500.
  #energy_unit           : string = "keV"

  ### Only for "spectrum" mode:
  #spectrum.data_file    : string = "${SNGENBB_DATA_DIR}/testing/data/sample_tabulated_energy_spectrum.data"

  randomized_direction   : boolean = 1
#+END_SRC


** TODO Combined generators
Combination of several =genbb= generators can be done using
=genbb::combined_particle_generator= object...
