#+TITLE:  SNGenbb Manager Configuration
#+AUTHOR: Xavier Garrido
#+DATE:   2013-03-04
#+OPTIONS: ^:{}
#+STARTUP: entitiespretty

* Introduction

The =genbb= package is dedicated to the generation of double beta decay and/or
radioactive background primary events as input for a simulation program.

More details concerning the use of =genbb= can be found in [[https://nemo.lpc-caen.in2p3.fr/wiki/genbb_help][LPC wiki]].

* Manager configuration
:PROPERTIES:
:TANGLE: sngenbb_manager.conf
:END:
** Genbb manager configuration
Here, general options such as verbosity, debug flags are passed to =genbb=
manager.
#+BEGIN_SRC shell
  #@config Main configuration parameters for the genbb manager

  #@description Logging priority
  logging.priority : string = "warning"

  #@description List of files containing particle generator definition rules
  generators.configuration_files : string[5] as path = \
      "@falaise:config/common/simulation/primary_events/1.0/background.def"  \
      "@falaise:config/common/simulation/primary_events/1.0/calibration.def" \
      "@falaise:config/common/simulation/primary_events/1.0/dbd.def"         \
      "@falaise:config/common/simulation/primary_events/1.0/misc.def"        \
      "@SNEMO_SIMULATION_CONFIGURATION@/sngenbb_wrappers.conf"
#+END_SRC

* Genbb wrappers
:PROPERTIES:
:TANGLE: sngenbb_wrappers.conf
:END:

This section holds the configuration of several =genbb= wrappers.

#+BEGIN_SRC shell
  #@description A sample list of setups
  #@key_label   "name"
  #@meta_label  "type"
#+END_SRC

** 2\nu2\beta isotope with energy cut
#+BEGIN_SRC shell
  [name="Se82.2nubb-2MeV" type="genbb::wdecay0"]
  #@config Two neutrino double beta decay of Se-82, 2nubb [DBD]
  decay_type      : string  = "DBD"
  decay_isotope   : string  = "Se82"
  decay_dbd_level : integer = 0
  decay_dbd_mode  : integer = 4
  energy_min      : real as energy = 2.0 MeV
#+END_SRC
** \nbsp^{96}Zr excited state
#+BEGIN_SRC shell
  [name="Zr96.2nubb" type="genbb::wdecay0"]
  #@config Two neutrino double beta decay of Zr-96, 2nubb [DBD]
  decay_type      : string  = "DBD"
  decay_isotope   : string  = "Zr96"
  decay_dbd_level : integer = 2
  decay_dbd_mode  : integer = 4 # 2nubb
#+END_SRC

** \nbsp^{222}Rn in the tracking chamber
Here, we use the same definition as =Bi214_Po214= that can be find in
=@falaise:config/common/simulation/primary_events/1.0/background.def=. We just
change the =genbb= label to distinguish the\nbsp^{214}Bi events generated in the
source foil to the ones generated in the tracking chamber.

#+BEGIN_SRC shell
  [name="Rn222" type="genbb::wdecay0"]
  #@config Bi-214/Po-214 decay in the tracker [background]
  decay_type      : string  = "background"
  decay_isotope   : string  = "Bi214+Po214"
#+END_SRC
** Radioelement wrappers
This part basically provides additionnal event generator wrappers for
SuperNEMO.

*** \nbsp^{214}Pb 0\nu\beta\beta
Following a [[http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=2946][talk]] given by Vladimir Treytak during Bratislava collaboration
meeting, 2013,\nbsp^{214}Pb is also a 2\beta emitter
#+BEGIN_SRC shell
  [name="Pb214.0nubb" type="genbb::wdecay0"]
  #@config Neutrinoless double beta decay of Pb-214 [DBD]
  decay_type      : string  = "DBD"
  decay_isotope   : string  = "Pb214"
  decay_dbd_level : integer = 0
  decay_dbd_mode  : integer = 1
#+END_SRC

** Single particle generators
Here, single particle can be generated using different energy distribution : fix
energy, flat energy distribution given energy limits, gaussian energy
distribution or following a tabulated energy spectrum.

*** Single monokinetic electron
#+BEGIN_SRC shell
  [name="electron_monokinetic" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "monokinetic"

  #@description Value of the particle energy
  energy : real as energy = 1000. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC

*** Single electron with flat energy distribution
#+BEGIN_SRC shell
  [name="electron_0-3MeV_flat" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "energy_range"

  #@description Minimal energy value
  min_energy : real as energy =    0. keV

  #@description Maximal energy value
  max_energy : real as energy = 3000. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC

*** Single electron with gaussian energy distribution
#+BEGIN_SRC shell
  [name="electron_gaussian_energy" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "energy_range"

  #@description Mean energy for the gaussian distribution
  mean_energy : real as energy = 1000. keV

  #@description Sigma value for the gaussian distribution
  sigma_energy : real as energy =  100. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC

*** Single electron with conic emission
#+BEGIN_SRC shell
  [name="electron_monokinetic_with_cone" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "monokinetic"

  #@description Direction of the emitted particle
  emission_direction : string = "cone"

  #@description The emission cone axis (values: "+x", "-x", "+y", "-y", "+z", "-z", "30.0 45.0 degree")
  cone.axis : string = "-z"

  #@description The default implicit angle unit
  angle_unit : string = "degree"

  #@description The minimum emission angle (cone)
  cone.min_angle : real as angle = 0 degree

  #@description The maximum emission angle (cone)
  cone.max_angle : real as angle = 10 degree

  #@description The kinetic energy of the generated particle
  energy : real as energy = 3000 keV
#+END_SRC

*** Single gamma with monokinetic energy
#+BEGIN_SRC shell
  [name="gamma_monokinetic" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "gamma"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "monokinetic"

  #@description Value of the particle energy
  energy : real as energy = 500. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC
*** Single gamma with flat energy distribution
#+BEGIN_SRC shell
  [name="gamma_0-3MeV_flat" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "gamma"

  #@description Flag for random emission
  emission_direction : string = "randomized"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "energy_range"

  #@description Minimal value of the particle energy
  min_energy : real as energy = 0. MeV

  #@description Maximal value of the particle energy
  max_energy : real as energy = 3. MeV
#+END_SRC

*** Multi-\gamma-rays

#+BEGIN_SRC shell
  [name="multi_gamma_rays" type="genbb::single_particle_generator"]

  #@config Parameters for the generation of multiple gamma rays

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "gamma"

  #@description Flag for random emission
  emission_direction : string = "randomized"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "multi_rays"

  #@description Energy unit
  energy_unit : string = "keV"

  #@description Particle energies
  multi_rays.energies : real[9] in keV = 53.161 79.6139 80.9971 160.613 223.234 276.398 302.853 356.017 383.851

  #@description Particle relative probabilities
  multi_rays.probabilities : real[9] = 0.02199 0.0262 0.0406 0.00645 0.00450 0.07164 0.1833 0.6205 0.0894
#+END_SRC

*** Single monokinetic alpha
#+BEGIN_SRC shell
  [name="alpha_monokinetic" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "alpha"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "monokinetic"

  #@description Value of the particle energy
  energy : real as energy = 7000. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC

** Combined generators
Combination of several =genbb= generators can be done using
=genbb::combined_particle_generator= object...

*** Simultaneous \gamma-rays
#+BEGIN_SRC shell
  [name="multi_gamma_particles" type="genbb::combined_particle_generator"]

  #@config A model that generates several particles  at the same time

  #@description Logging priority
  logging.priority : string = "warning"

  #@description Assign unique generation id
  assign_generation_ids : boolean = true

  #@description The mode ("timing", "plain_probability" or "activity")
  mode : string = "time"

  #@description The list of particle generators that compose the combo
  generators.labels : string[3] = \
                    "gamma1"      \
                    "gamma1"      \
                    "gamma1"

  #@description The name of the generator associated the "gamma1" contribution
  generators.gamma1.name : string = "gamma_monokinetic"

  #@description The time mode associated to the "gamma1" contribution
  generators.gamma1.time_mode : string = "fixed"

  #@description The shift time associated to the "gamma1" contribution
  generators.gamma1.fixed_time : real as time = 0 ns

  #@description The name of the generator associated the "gamma2" contribution
  generators.gamma2.name : string = "gamma_monokinetic"

  #@description The time mode associated to the "gamma2" contribution
  generators.gamma2.time_mode : string = "fixed"

  #@description The shift time associated to the "gamma2" contribution
  generators.gamma2.fixed_time : real as time = 0 ns
#+END_SRC

*** Multi-particles gun

#+BEGIN_SRC shell
  [name="electron_monokinetic1" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "monokinetic"

  #@description Value of the particle energy
  energy : real as energy = 1000. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC

#+BEGIN_SRC shell
  [name="electron_monokinetic2" type="genbb::single_particle_generator"]

  #@config Parameters for the "single_particle" mode (class genbb::single_particle_generator):

  #@description Generated particle ("electron", "positron", "gamma", "alpha"):
  particle_name : string = "electron"

  #@description Mode ("energy_range", "gaussian_energy", "monokinetic", "spectrum"):
  mode : string = "monokinetic"

  #@description Value of the particle energy
  energy : real as energy = 3000. keV

  #@description Flag for random emission
  emission_direction : string = "randomized"
#+END_SRC

#+BEGIN_SRC shell
  [name="multi_particles" type="genbb::combined_particle_generator"]

  #@config A model that generates several particles  at the same time

  #@description Logging priority
  logging.priority : string = "warning"

  #@description Assign unique generation id
  assign_generation_ids : boolean = true

  #@description The mode ("timing", "plain_probability" or "activity")
  mode : string = "time"

  #@description The list of particle generators that compose the combo
  generators.labels : string[3] = \
                    "electron1"   \
                    "electron2"   \
                    "gamma1"

  #@description The name of the generator associated the "electron1" contribution
  generators.electron1.name : string = "electron_monokinetic1"

  #@description The time mode associated to the "electron1" contribution
  generators.electron1.time_mode : string = "fixed"

  #@description The shift time associated to the "electron1" contribution
  generators.electron1.fixed_time : real as time = 0 ns

  #@description The name of the generator associated the "electron2" contribution
  generators.electron2.name : string = "electron_monokinetic1"

  #@description The time mode associated to the "electron2" contribution
  generators.electron2.time_mode : string = "fixed"

  #@description The shift time associated to the "electron2" contribution
  generators.electron2.fixed_time : real as time = 0 ns

  #@description The name of the generator associated the "gamma1" contribution
  generators.gamma1.name : string = "gamma_monokinetic"

  #@description The time mode associated to the "electron2" contribution
  generators.gamma1.time_mode : string = "fixed"

  #@description The shift time associated to the "electron2" contribution
  generators.gamma1.fixed_time : real as time = 0 ns
#+END_SRC
